/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppAutocomplete: typeof import('./resources/js/@core/components/app-form-elements/AppAutocomplete.vue')['default']
    AppBarSearch: typeof import('./resources/js/@core/components/AppBarSearch.vue')['default']
    AppCardActions: typeof import('./resources/js/@core/components/cards/AppCardActions.vue')['default']
    AppCardCode: typeof import('./resources/js/@core/components/cards/AppCardCode.vue')['default']
    AppCombobox: typeof import('./resources/js/@core/components/app-form-elements/AppCombobox.vue')['default']
    AppDateTimePicker: typeof import('./resources/js/@core/components/app-form-elements/AppDateTimePicker.vue')['default']
    AppDrawerHeaderSection: typeof import('./resources/js/@core/components/AppDrawerHeaderSection.vue')['default']
    AppSelect: typeof import('./resources/js/@core/components/app-form-elements/AppSelect.vue')['default']
    AppStepper: typeof import('./resources/js/@core/components/AppStepper.vue')['default']
    AppTextarea: typeof import('./resources/js/@core/components/app-form-elements/AppTextarea.vue')['default']
    AppTextField: typeof import('./resources/js/@core/components/app-form-elements/AppTextField.vue')['default']
    BuyNow: typeof import('./resources/js/@core/components/BuyNow.vue')['default']
    CardStatisticsHorizontal: typeof import('./resources/js/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./resources/js/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsVerticalSimple: typeof import('./resources/js/@core/components/CardStatisticsVerticalSimple.vue')['default']
    CustomCheckboxes: typeof import('./resources/js/@core/components/app-form-elements/CustomCheckboxes.vue')['default']
    CustomCheckboxesWithIcon: typeof import('./resources/js/@core/components/app-form-elements/CustomCheckboxesWithIcon.vue')['default']
    CustomCheckboxesWithImage: typeof import('./resources/js/@core/components/app-form-elements/CustomCheckboxesWithImage.vue')['default']
    CustomizerSection: typeof import('./resources/js/@core/components/CustomizerSection.vue')['default']
    CustomRadios: typeof import('./resources/js/@core/components/app-form-elements/CustomRadios.vue')['default']
    CustomRadiosWithIcon: typeof import('./resources/js/@core/components/app-form-elements/CustomRadiosWithIcon.vue')['default']
    CustomRadiosWithImage: typeof import('./resources/js/@core/components/app-form-elements/CustomRadiosWithImage.vue')['default']
    DialogCloseBtn: typeof import('./resources/js/@core/components/DialogCloseBtn.vue')['default']
    DropZone: typeof import('./resources/js/@core/components/DropZone.vue')['default']
    I18n: typeof import('./resources/js/@core/components/I18n.vue')['default']
    MoreBtn: typeof import('./resources/js/@core/components/MoreBtn.vue')['default']
    Notifications: typeof import('./resources/js/@core/components/Notifications.vue')['default']
    ProductDescriptionEditor: typeof import('./resources/js/@core/components/ProductDescriptionEditor.vue')['default']
    ScrollToTop: typeof import('./resources/js/@core/components/ScrollToTop.vue')['default']
    Shortcuts: typeof import('./resources/js/@core/components/Shortcuts.vue')['default']
    TablePagination: typeof import('./resources/js/@core/components/TablePagination.vue')['default']
    TheCustomizer: typeof import('./resources/js/@core/components/TheCustomizer.vue')['default']
    ThemeSwitcher: typeof import('./resources/js/@core/components/ThemeSwitcher.vue')['default']
    TiptapEditor: typeof import('./resources/js/@core/components/TiptapEditor.vue')['default']
  }
}

// For TSX support
declare global {
  const AppAutocomplete: typeof import('./resources/js/@core/components/app-form-elements/AppAutocomplete.vue')['default']
  const AppBarSearch: typeof import('./resources/js/@core/components/AppBarSearch.vue')['default']
  const AppCardActions: typeof import('./resources/js/@core/components/cards/AppCardActions.vue')['default']
  const AppCardCode: typeof import('./resources/js/@core/components/cards/AppCardCode.vue')['default']
  const AppCombobox: typeof import('./resources/js/@core/components/app-form-elements/AppCombobox.vue')['default']
  const AppDateTimePicker: typeof import('./resources/js/@core/components/app-form-elements/AppDateTimePicker.vue')['default']
  const AppDrawerHeaderSection: typeof import('./resources/js/@core/components/AppDrawerHeaderSection.vue')['default']
  const AppSelect: typeof import('./resources/js/@core/components/app-form-elements/AppSelect.vue')['default']
  const AppStepper: typeof import('./resources/js/@core/components/AppStepper.vue')['default']
  const AppTextarea: typeof import('./resources/js/@core/components/app-form-elements/AppTextarea.vue')['default']
  const AppTextField: typeof import('./resources/js/@core/components/app-form-elements/AppTextField.vue')['default']
  const BuyNow: typeof import('./resources/js/@core/components/BuyNow.vue')['default']
  const CardStatisticsHorizontal: typeof import('./resources/js/@core/components/cards/CardStatisticsHorizontal.vue')['default']
  const CardStatisticsVertical: typeof import('./resources/js/@core/components/cards/CardStatisticsVertical.vue')['default']
  const CardStatisticsVerticalSimple: typeof import('./resources/js/@core/components/CardStatisticsVerticalSimple.vue')['default']
  const CustomCheckboxes: typeof import('./resources/js/@core/components/app-form-elements/CustomCheckboxes.vue')['default']
  const CustomCheckboxesWithIcon: typeof import('./resources/js/@core/components/app-form-elements/CustomCheckboxesWithIcon.vue')['default']
  const CustomCheckboxesWithImage: typeof import('./resources/js/@core/components/app-form-elements/CustomCheckboxesWithImage.vue')['default']
  const CustomizerSection: typeof import('./resources/js/@core/components/CustomizerSection.vue')['default']
  const CustomRadios: typeof import('./resources/js/@core/components/app-form-elements/CustomRadios.vue')['default']
  const CustomRadiosWithIcon: typeof import('./resources/js/@core/components/app-form-elements/CustomRadiosWithIcon.vue')['default']
  const CustomRadiosWithImage: typeof import('./resources/js/@core/components/app-form-elements/CustomRadiosWithImage.vue')['default']
  const DialogCloseBtn: typeof import('./resources/js/@core/components/DialogCloseBtn.vue')['default']
  const DropZone: typeof import('./resources/js/@core/components/DropZone.vue')['default']
  const I18n: typeof import('./resources/js/@core/components/I18n.vue')['default']
  const MoreBtn: typeof import('./resources/js/@core/components/MoreBtn.vue')['default']
  const Notifications: typeof import('./resources/js/@core/components/Notifications.vue')['default']
  const ProductDescriptionEditor: typeof import('./resources/js/@core/components/ProductDescriptionEditor.vue')['default']
  const ScrollToTop: typeof import('./resources/js/@core/components/ScrollToTop.vue')['default']
  const Shortcuts: typeof import('./resources/js/@core/components/Shortcuts.vue')['default']
  const TablePagination: typeof import('./resources/js/@core/components/TablePagination.vue')['default']
  const TheCustomizer: typeof import('./resources/js/@core/components/TheCustomizer.vue')['default']
  const ThemeSwitcher: typeof import('./resources/js/@core/components/ThemeSwitcher.vue')['default']
  const TiptapEditor: typeof import('./resources/js/@core/components/TiptapEditor.vue')['default']
}